### ISSUE TITLE
Automatic tool switch

### ISSUE THREAD

**Issue by mferbel** [happyredstone/sodiumplus#18]
Hello,

I have an issue and i can't find what mod causes it.
When having 2 pickaxes in the hotbar (in slots 2 and 3), as soon as i mine a block with the pickaxe in slot 3, it switches automatically to the one in slot 2.

Please is this a bug or an intended feature, and how could I fix it ?

**Comment by NoSadBeHappy** [comment]
This might be due to a mod (i forgot which one and couldn't find it) that will replenish a pickaxe or other items in your hotbar. What I would do, is remove half of the mods, see if it still happens, and then remove another half and so on so that you can find what mod does it. Sorry im not more helpful, i have been busy these past couple days. If this issue is still here in a little while I will help fegure out the problem.

**Comment by ikon106** [comment]
Did any of you figure out which one it is?

**Comment by NoSadBeHappy** [comment]
This mod has been removed in the new versions of the pack.
